# Generated by Django 5.2.6 on 2025-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='max_hours_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='min_hours_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('AP', 'Assistant Professor'), ('ASP', 'Associate Professor'), ('P', 'Professor')], default='AP', max_length=3),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultyassignment',
            name='responsibility',
            field=models.CharField(choices=[('ALL', 'All Classes'), ('THEORY', 'Theory Only'), ('TUTORIAL', 'Tutorial Only')], default='ALL', max_length=20),
        ),
    ]
